In [8]:
import numpy as np

# Data Loading

In [6]:
matrix = np.loadtxt('matrix.csv', delimiter=',')
vector = np.load('vector.npy')

In [10]:
print(matrix)
print(vector)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[10]
 [20]
 [15]]


# For loop implementation

In [13]:
def vmm_dot(A, x):
    output = np.zeros((A.shape[0], 1))
    for r in range(A.shape[0]):
        acc = 0
        for c in range(A.shape[1]):
            acc += matrix[r, c] * vector[c]
        output[r] = acc
    return output

In [17]:
output = vmm_dot(matrix, vector)
np.savetxt('output_forloop.csv', output)

# `np.dot`

In [18]:
output_2 = np.dot(matrix, vector)
np.save('output_dot.npy', output_2)

# Output Difference

In [21]:
diff = output_2 - output
np.savetxt('output_difference.csv', diff)

All values in the saved csv are zero, indicating that the two outputs agree to within the precision of floating point numbers. Although in this case the values are equal, it does not mean that the code is correct. It is only indicating that in this scenario it is correct. For example, I *could* have implemented a function that returns the hardcoded result returned by `np.dot`. 